! ============================================================
! CE1 – Customer Edge (Branch Site)
! Role  : eBGP peer to PE1, IPSec tunnel endpoint to CE2
! Links : eth1 -> PE1 (10.0.12.0/30)
! Loopback: 10.0.0.1/32  AS 65001
! ============================================================

frr version 8.4.0
frr defaults traditional
hostname ce1
log syslog informational
service integrated-vtysh-config

!
interface lo
 ip address 10.0.0.1/32
!
interface eth1
 description ce1->pe1
 ip address 10.0.12.1/30
!

! ---- eBGP to PE1 (VRF CUST peer, AS 100) ----
router bgp 65001
 bgp router-id 10.0.0.1
 bgp log-neighbor-changes
 !
 neighbor 10.0.12.2 remote-as 100
 neighbor 10.0.12.2 description PE1-eBGP
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
  neighbor 10.0.12.2 activate
  neighbor 10.0.12.2 soft-reconfiguration inbound
 exit-address-family
!

line vty
!
end
