! ============================================================
! CE2 – Customer Edge (Datacenter Site)
! Role  : eBGP peer to PE2, IPSec tunnel endpoint to CE1
! Links : eth1 -> PE2 (10.0.45.0/30)
! Loopback: 10.0.0.2/32  AS 65002
! ============================================================

frr version 8.4.0
frr defaults traditional
hostname ce2
log syslog informational
service integrated-vtysh-config

!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 description ce2->pe2
 ip address 10.0.45.2/30
!

! ---- eBGP to PE2 (VRF CUST peer, AS 100) ----
router bgp 65002
 bgp router-id 10.0.0.2
 bgp log-neighbor-changes
 !
 neighbor 10.0.45.1 remote-as 100
 neighbor 10.0.45.1 description PE2-eBGP
 !
 address-family ipv4 unicast
  network 10.0.0.2/32
  neighbor 10.0.45.1 activate
  neighbor 10.0.45.1 soft-reconfiguration inbound
 exit-address-family
!

line vty
!
end
